# Generated by Django 3.2.9 on 2021-12-13 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_of_nko', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publication',
            new_name='The_Rest_of_Publication',
        ),
    ]
